[package]
name = "spotify_tracker"
version = "0.1.0"
authors = ["Tanay Nathan <tanaynathan14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.6.0"
dotenv = "0.14.1"
diesel = { version = "1.4.2", features = ["postgres", "chrono"] }
warp = "0.1.18"
